// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1PayInvoiceResponse v1 pay invoice response
//
// swagger:model v1PayInvoiceResponse
type V1PayInvoiceResponse interface{}
