// Code generated by mockery v2.47.0. DO NOT EDIT.

package command

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCommands is an autogenerated mock type for the Commands type
type MockCommands struct {
	mock.Mock
}

// ApproveOrder provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) ApproveOrder(ctx context.Context, cmd ApproveOrder) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for ApproveOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ApproveOrder) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CancelOrder provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) CancelOrder(ctx context.Context, cmd CancelOrder) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, CancelOrder) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CompleteOrder provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) CompleteOrder(ctx context.Context, cmd CompleteOrder) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CompleteOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, CompleteOrder) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateOrder provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) CreateOrder(ctx context.Context, cmd CreateOrder) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, CreateOrder) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadyOrder provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) ReadyOrder(ctx context.Context, cmd ReadyOrder) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for ReadyOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ReadyOrder) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RejectOrder provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) RejectOrder(ctx context.Context, cmd RejectOrder) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RejectOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, RejectOrder) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockCommands creates a new instance of MockCommands. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommands(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommands {
	mock := &MockCommands{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
