// Code generated by mockery v2.47.0. DO NOT EDIT.

package mapper

import (
	aggregate "github.com/Chengxufeng1994/event-driven-arch-in-go/payment/internal/domain/aggregate"
	mock "github.com/stretchr/testify/mock"

	po "github.com/Chengxufeng1994/event-driven-arch-in-go/payment/internal/infrastructure/persistence/gorm/po"
)

// MockPaymentMapperIntf is an autogenerated mock type for the PaymentMapperIntf type
type MockPaymentMapperIntf struct {
	mock.Mock
}

// ToDomain provides a mock function with given fields: payment
func (_m *MockPaymentMapperIntf) ToDomain(payment *po.Payment) (*aggregate.PaymentAgg, error) {
	ret := _m.Called(payment)

	if len(ret) == 0 {
		panic("no return value specified for ToDomain")
	}

	var r0 *aggregate.PaymentAgg
	var r1 error
	if rf, ok := ret.Get(0).(func(*po.Payment) (*aggregate.PaymentAgg, error)); ok {
		return rf(payment)
	}
	if rf, ok := ret.Get(0).(func(*po.Payment) *aggregate.PaymentAgg); ok {
		r0 = rf(payment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aggregate.PaymentAgg)
		}
	}

	if rf, ok := ret.Get(1).(func(*po.Payment) error); ok {
		r1 = rf(payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ToPersistent provides a mock function with given fields: payment
func (_m *MockPaymentMapperIntf) ToPersistent(payment *aggregate.PaymentAgg) (*po.Payment, error) {
	ret := _m.Called(payment)

	if len(ret) == 0 {
		panic("no return value specified for ToPersistent")
	}

	var r0 *po.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(*aggregate.PaymentAgg) (*po.Payment, error)); ok {
		return rf(payment)
	}
	if rf, ok := ret.Get(0).(func(*aggregate.PaymentAgg) *po.Payment); ok {
		r0 = rf(payment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*po.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(*aggregate.PaymentAgg) error); ok {
		r1 = rf(payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPaymentMapperIntf creates a new instance of MockPaymentMapperIntf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentMapperIntf(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentMapperIntf {
	mock := &MockPaymentMapperIntf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
