openapiOptions:
  file:
    - file: "api/depot/v1/depot.proto"
      option:
        info:
          title: Depot Operations
          version: "1.0.0"
        basePath: /
  method:
    - method: api.depot.v1.DepotService.CreateShoppingList
      option:
        operationId: createShoppingList
        tags:
          - ShoppingList
        summary: Schedule shopping tasks for an order
    - method: api.depot.v1.DepotService.CancelShoppingList
      option:
        operationId: cancelShoppingList
        tags:
          - ShoppingList
        summary: Cancel a shopping task
    - method: api.depot.v1.DepotService.AssignShoppingList
      option:
        operationId: assignShoppingList
        tags:
          - ShoppingList
        summary: Assign a shopping list to a bot
    - method: api.depot.v1.DepotService.CompleteShoppingList
      option:
        operationId: completeShoppingList
        tags:
          - ShoppingList
        summary: Complete a shopping task
