include:
  - docker-compose.infra.yaml
services:
  monolith_debug:
    container_name: monolith_debug
    build:
      context: .
      dockerfile: build/docker/Dockerfile.debug
    environment:
      - EDA_INFRASTRUCTURE_GORM_DSN=host=postgres user=postgres password=postgres dbname=mallbots port=5432 sslmode=disable TimeZone=Asia/Taipei
      - EDA_INFRASTRUCTURE_NATS_URL=nats://nats:4222
    ports:
      - 8080:8080
      - 8081:8081
      - 2345:2345
    depends_on:
      - nats
      - postgres
    command: ["/wait-for", "postgres:5432", "--", "/dlv", "exec", "--listen=:2345", "--headless=true", "--continue", "--api-version=2", "--accept-multiclient", "/mallbots/monolith"]
    networks:
      eda_network:
        ipv4_address: 10.5.0.10
    profiles:
      - debug

  monolith:
    container_name: monolith
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    environment:
      - EDA_INFRASTRUCTURE_GORM_DSN=host=postgres user=postgres password=postgres dbname=mallbots port=5432 sslmode=disable TimeZone=Asia/Taipei
      - EDA_INFRASTRUCTURE_NATS_URL=nats://nats:4222
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - nats
      - postgres
    command: [ "./wait-for", "postgres:5432", "--", "/mallbots/monolith" ]
    profiles:
      - monolith
    networks:
      eda_network:
        ipv4_address: 10.5.0.10

networks:
  eda_network:
    name: eda_network
    driver: bridge
    ipam:
      config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
