// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Basketv1Item basketv1 item
//
// swagger:model basketv1Item
type Basketv1Item struct {

	// product Id
	ProductID string `json:"productId,omitempty"`

	// product name
	ProductName string `json:"productName,omitempty"`

	// product price
	ProductPrice float64 `json:"productPrice,omitempty"`

	// quantity
	Quantity int32 `json:"quantity,omitempty"`

	// store Id
	StoreID string `json:"storeId,omitempty"`

	// store name
	StoreName string `json:"storeName,omitempty"`
}

// Validate validates this basketv1 item
func (m *Basketv1Item) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this basketv1 item based on context it is used
func (m *Basketv1Item) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Basketv1Item) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Basketv1Item) UnmarshalBinary(b []byte) error {
	var res Basketv1Item
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
