// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1AddItemResponse v1 add item response
//
// swagger:model v1AddItemResponse
type V1AddItemResponse interface{}
