// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1CheckoutBasketResponse v1 checkout basket response
//
// swagger:model v1CheckoutBasketResponse
type V1CheckoutBasketResponse interface{}
