// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1StartBasketRequest v1 start basket request
//
// swagger:model v1StartBasketRequest
type V1StartBasketRequest struct {

	// customer Id
	CustomerID string `json:"customerId,omitempty"`
}

// Validate validates this v1 start basket request
func (m *V1StartBasketRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 start basket request based on context it is used
func (m *V1StartBasketRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1StartBasketRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1StartBasketRequest) UnmarshalBinary(b []byte) error {
	var res V1StartBasketRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
