// Code generated by go-swagger; DO NOT EDIT.

package shopping_list

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Chengxufeng1994/event-driven-arch-in-go/depot/depotclient/models"
)

// CompleteShoppingListReader is a Reader for the CompleteShoppingList structure.
type CompleteShoppingListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CompleteShoppingListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCompleteShoppingListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCompleteShoppingListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCompleteShoppingListOK creates a CompleteShoppingListOK with default headers values
func NewCompleteShoppingListOK() *CompleteShoppingListOK {
	return &CompleteShoppingListOK{}
}

/*
CompleteShoppingListOK describes a response with status code 200, with default header values.

A successful response.
*/
type CompleteShoppingListOK struct {
	Payload models.V1CompleteShoppingListResponse
}

// IsSuccess returns true when this complete shopping list o k response has a 2xx status code
func (o *CompleteShoppingListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this complete shopping list o k response has a 3xx status code
func (o *CompleteShoppingListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this complete shopping list o k response has a 4xx status code
func (o *CompleteShoppingListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this complete shopping list o k response has a 5xx status code
func (o *CompleteShoppingListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this complete shopping list o k response a status code equal to that given
func (o *CompleteShoppingListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the complete shopping list o k response
func (o *CompleteShoppingListOK) Code() int {
	return 200
}

func (o *CompleteShoppingListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/depots/shopping/{id}/complete][%d] completeShoppingListOK %s", 200, payload)
}

func (o *CompleteShoppingListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/depots/shopping/{id}/complete][%d] completeShoppingListOK %s", 200, payload)
}

func (o *CompleteShoppingListOK) GetPayload() models.V1CompleteShoppingListResponse {
	return o.Payload
}

func (o *CompleteShoppingListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCompleteShoppingListDefault creates a CompleteShoppingListDefault with default headers values
func NewCompleteShoppingListDefault(code int) *CompleteShoppingListDefault {
	return &CompleteShoppingListDefault{
		_statusCode: code,
	}
}

/*
CompleteShoppingListDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type CompleteShoppingListDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this complete shopping list default response has a 2xx status code
func (o *CompleteShoppingListDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this complete shopping list default response has a 3xx status code
func (o *CompleteShoppingListDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this complete shopping list default response has a 4xx status code
func (o *CompleteShoppingListDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this complete shopping list default response has a 5xx status code
func (o *CompleteShoppingListDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this complete shopping list default response a status code equal to that given
func (o *CompleteShoppingListDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the complete shopping list default response
func (o *CompleteShoppingListDefault) Code() int {
	return o._statusCode
}

func (o *CompleteShoppingListDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/depots/shopping/{id}/complete][%d] completeShoppingList default %s", o._statusCode, payload)
}

func (o *CompleteShoppingListDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/v1/depots/shopping/{id}/complete][%d] completeShoppingList default %s", o._statusCode, payload)
}

func (o *CompleteShoppingListDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *CompleteShoppingListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
