// Code generated by go-swagger; DO NOT EDIT.

package shopping_list

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Chengxufeng1994/event-driven-arch-in-go/depot/depotclient/models"
)

// NewCompleteShoppingListParams creates a new CompleteShoppingListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCompleteShoppingListParams() *CompleteShoppingListParams {
	return &CompleteShoppingListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCompleteShoppingListParamsWithTimeout creates a new CompleteShoppingListParams object
// with the ability to set a timeout on a request.
func NewCompleteShoppingListParamsWithTimeout(timeout time.Duration) *CompleteShoppingListParams {
	return &CompleteShoppingListParams{
		timeout: timeout,
	}
}

// NewCompleteShoppingListParamsWithContext creates a new CompleteShoppingListParams object
// with the ability to set a context for a request.
func NewCompleteShoppingListParamsWithContext(ctx context.Context) *CompleteShoppingListParams {
	return &CompleteShoppingListParams{
		Context: ctx,
	}
}

// NewCompleteShoppingListParamsWithHTTPClient creates a new CompleteShoppingListParams object
// with the ability to set a custom HTTPClient for a request.
func NewCompleteShoppingListParamsWithHTTPClient(client *http.Client) *CompleteShoppingListParams {
	return &CompleteShoppingListParams{
		HTTPClient: client,
	}
}

/*
CompleteShoppingListParams contains all the parameters to send to the API endpoint

	for the complete shopping list operation.

	Typically these are written to a http.Request.
*/
type CompleteShoppingListParams struct {

	// Body.
	Body models.DepotServiceCompleteShoppingListBody

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the complete shopping list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CompleteShoppingListParams) WithDefaults() *CompleteShoppingListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the complete shopping list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CompleteShoppingListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the complete shopping list params
func (o *CompleteShoppingListParams) WithTimeout(timeout time.Duration) *CompleteShoppingListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the complete shopping list params
func (o *CompleteShoppingListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the complete shopping list params
func (o *CompleteShoppingListParams) WithContext(ctx context.Context) *CompleteShoppingListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the complete shopping list params
func (o *CompleteShoppingListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the complete shopping list params
func (o *CompleteShoppingListParams) WithHTTPClient(client *http.Client) *CompleteShoppingListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the complete shopping list params
func (o *CompleteShoppingListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the complete shopping list params
func (o *CompleteShoppingListParams) WithBody(body models.DepotServiceCompleteShoppingListBody) *CompleteShoppingListParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the complete shopping list params
func (o *CompleteShoppingListParams) SetBody(body models.DepotServiceCompleteShoppingListBody) {
	o.Body = body
}

// WithID adds the id to the complete shopping list params
func (o *CompleteShoppingListParams) WithID(id string) *CompleteShoppingListParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the complete shopping list params
func (o *CompleteShoppingListParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CompleteShoppingListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
