// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1CreateStoreRequest v1 create store request
//
// swagger:model v1CreateStoreRequest
type V1CreateStoreRequest struct {

	// location
	Location string `json:"location,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this v1 create store request
func (m *V1CreateStoreRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 create store request based on context it is used
func (m *V1CreateStoreRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1CreateStoreRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1CreateStoreRequest) UnmarshalBinary(b []byte) error {
	var res V1CreateStoreRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
