// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1DecreaseProductPriceResponse v1 decrease product price response
//
// swagger:model v1DecreaseProductPriceResponse
type V1DecreaseProductPriceResponse interface{}
