// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1EnableParticipationResponse v1 enable participation response
//
// swagger:model v1EnableParticipationResponse
type V1EnableParticipationResponse interface{}
