// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1GetStoreResponse v1 get store response
//
// swagger:model v1GetStoreResponse
type V1GetStoreResponse struct {

	// store
	Store *V1Store `json:"store,omitempty"`
}

// Validate validates this v1 get store response
func (m *V1GetStoreResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStore(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1GetStoreResponse) validateStore(formats strfmt.Registry) error {
	if swag.IsZero(m.Store) { // not required
		return nil
	}

	if m.Store != nil {
		if err := m.Store.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("store")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("store")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 get store response based on the context it is used
func (m *V1GetStoreResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateStore(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1GetStoreResponse) contextValidateStore(ctx context.Context, formats strfmt.Registry) error {

	if m.Store != nil {

		if swag.IsZero(m.Store) { // not required
			return nil
		}

		if err := m.Store.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("store")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("store")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1GetStoreResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1GetStoreResponse) UnmarshalBinary(b []byte) error {
	var res V1GetStoreResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
