// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1RebrandStoreResponse v1 rebrand store response
//
// swagger:model v1RebrandStoreResponse
type V1RebrandStoreResponse interface{}
