// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Orderv1Item orderv1 item
//
// swagger:model orderv1Item
type Orderv1Item struct {

	// price
	Price float64 `json:"price,omitempty"`

	// product Id
	ProductID string `json:"productId,omitempty"`

	// product name
	ProductName string `json:"productName,omitempty"`

	// quantity
	Quantity int32 `json:"quantity,omitempty"`

	// store Id
	StoreID string `json:"storeId,omitempty"`

	// store name
	StoreName string `json:"storeName,omitempty"`
}

// Validate validates this orderv1 item
func (m *Orderv1Item) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this orderv1 item based on context it is used
func (m *Orderv1Item) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Orderv1Item) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Orderv1Item) UnmarshalBinary(b []byte) error {
	var res Orderv1Item
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
