// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1AssignShoppingListResponse v1 assign shopping list response
//
// swagger:model v1AssignShoppingListResponse
type V1AssignShoppingListResponse interface{}
