// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1CompleteShoppingListResponse v1 complete shopping list response
//
// swagger:model v1CompleteShoppingListResponse
type V1CompleteShoppingListResponse interface{}
