// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1DepotServiceCancelShoppingListBody v1 depot service cancel shopping list body
//
// swagger:model v1DepotServiceCancelShoppingListBody
type V1DepotServiceCancelShoppingListBody interface{}
