// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1OrderItem v1 order item
//
// swagger:model v1OrderItem
type V1OrderItem struct {

	// product Id
	ProductID string `json:"productId,omitempty"`

	// quantity
	Quantity int32 `json:"quantity,omitempty"`

	// store Id
	StoreID string `json:"storeId,omitempty"`
}

// Validate validates this v1 order item
func (m *V1OrderItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 order item based on context it is used
func (m *V1OrderItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1OrderItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1OrderItem) UnmarshalBinary(b []byte) error {
	var res V1OrderItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
