// Code generated by mockery v2.47.0. DO NOT EDIT.

package dao

import mock "github.com/stretchr/testify/mock"

// MockOrderDaoIntf is an autogenerated mock type for the OrderDaoIntf type
type MockOrderDaoIntf struct {
	mock.Mock
}

// NewMockOrderDaoIntf creates a new instance of MockOrderDaoIntf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderDaoIntf(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderDaoIntf {
	mock := &MockOrderDaoIntf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
