// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1Customer v1 customer
//
// swagger:model v1Customer
type V1Customer struct {

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// sms number
	SmsNumber string `json:"smsNumber,omitempty"`
}

// Validate validates this v1 customer
func (m *V1Customer) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 customer based on context it is used
func (m *V1Customer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1Customer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1Customer) UnmarshalBinary(b []byte) error {
	var res V1Customer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
