// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1DisableCustomerResponse v1 disable customer response
//
// swagger:model v1DisableCustomerResponse
type V1DisableCustomerResponse interface{}
